services:
  - type: web
    name: jessie-hope-portfolio
    env: node
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    nodeVersion: 20.11.1
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
    healthCheckPath: /
    autoDeploy: true 